apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zhzf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0084-tenant/ci10t-776-0084-app/devfile-sample-zhzf@sha256:78c37632bdcf3b108fbacfe52c6448275d9d74ec3378237d40de71f323ee2c59
        name: my-nodejs
        resources: {}
status: {}
